// tmp file is for testing out components, functions and other stuff

import React, { Component } from 'react';
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, ScrollView, View, Dimensions, Platform, TextInput } from 'react-native';
import { colour } from '../lib/Colours';
import Eqn from '../lib/Eqn';

class TMP extends Component {
	constructor() {
		super();
		this.state = {
			SCREEN_W: Dimensions.get('window').width,
			SCREEN_H: Dimensions.get('window').height,
			PLATF_OS: Platform.OS,
			input_field: '',
		}
		this.styles = StyleSheet.create({
			test: {

			},
			norm_txt: {
				fontWeight: 'normal',
				fontSize: 14,
				color: colour.light,
				textAlign: 'justify',
			},
			titl_txt: {
				paddingTop: 16,
				fontWeight: 'bold',
				fontSize: 16,
				color: colour.light,
				textAlign: 'left',
			}
		});
		this.input = this.input.bind(this);
		this.update_inp_field = this.update_inp_field.bind(this);
	}

	update_inp_field(text) {
		this.setState({input_field: text});
	}

	input() {
		return(
			<TextInput
				style={{
					width: '100%',
					padding: 16,
					height: 48,
					color: colour.dark,
					backgroundColor: colour.light,
					borderWidth: 2,
					borderColor: colour.light,
					fontWeight: 'normal',
					fontSize: 14,
					color: colour.dark,
				}}
				onChangeText={text => this.update_inp_field(text)} 
				placeholder='Type here...'
			/>
		)
	}
	
	render() {
		return(
			<ScrollView style={{
				backgroundColor: colour.dark,
				paddingHorizontal: this.state.PLATF_OS == 'web' ? 64 : 24,
				paddingVertical: this.state.PLATF_OS == 'web' ? 32 : 16,
			}}>
				<View style={{
					paddingBottom: 32,
				}}>
					{this.input()}
					<Text style={this.styles.titl_txt}>Title Example</Text>
					
					<Eqn ver={this.state.PLATF_OS}
						eqn='x=y'
					/>
					<Text style={this.styles.norm_txt}>
						TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE TMP PAGE
					</Text>
				</View>
			</ScrollView>
		)
	}
}

export { TMP };